on: push
name: AzureARMSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/arm-deploy@v1
      id: deploy  
      with:
        resourceGroupName: TestRG
        template: storageaccount/storage.json
        parameters: storageaccount/storage.parameters.json
        
    - run: echo ${{ steps.deploy.outputs.storageacc_name }}
    - name: get storage name
      env: 
       stg_name: ${{ steps.deploy.outputs.storageacc_name }}
       
    - name: print storage name
    - run: echo "my storage account name is $stg_name"
        
