on:
  workflow_dispatch
  
env:
  AZURE_FUNCTIONAPP_NAME: 'func-qrcodegenerator-dev-cus-001'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '5.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  Build:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      with:
          repository: pallakimalli/MyAzureRepo
          path: 'MyAzureRepo/ValmontApp.QRCode'
      
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: ls
       
    - name: Build with dotnet
      run: dotnet build "ValmontApp.QRCodeGeneration.csproj" --configuration Release
 
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      
    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v2
      with:
          name: Function-app
          path: '${{env.DOTNET_ROOT}}/myapp'
