on:
  workflow_dispatch:
env:
    DOTNET_VERSION: '6.0.11'
      
name: Test workflow  
jobs:
 test_job:
  runs-on: ubuntu-latest
  steps:
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
   
