on:
  workflow_dispatch
  
env:
  AZURE_FUNCTIONAPP_NAME: 'func-qrcodegenerator-dev-cus-001'   # set this to your function app name on Azure
      # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: '5.0.x'                   # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '${{ github.workspace }}/ValmontApp.QRCode'
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/build-artifacts'
  BUILD_PACKAGE_NAME: 'az-func.zip'
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: ls
       
    - name: 'Build and package code'
      shell: bash
      run: |
       	publishfolder="${{ github.workspace }}/output"
       	mkdir $publishfolder
       	cd $publishfolder
       	dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output .
       	mkdir ${{ env.BUILD_OUTPUT_PATH }}
       	zip -r ${{ env.BUILD_OUTPUT_PATH }}/${{ env.BUILD_PACKAGE_NAME }} .
        
    - name: 'Package Azure Function release build'
      uses: actions/upload-artifact@v2
      with:
       name: build_artifacts
       path: ${{ env.BUILD_OUTPUT_PATH }}
       if-no-files-found: error
